export const HG_CATEGORY_KEY = {
  ACCESSION: "accession",
  ANALYZE_GENOME: "analyzeGenome",
  ANNOTATION_STATUS: "annotationStatus",
  ASSEMBLY_COUNT: "assemblyCount",
  ASSEMBLY_TAXONOMY_IDS: "assemblyTaxonomyIds",
  CALC_CONTIG_N50: "calcContigN50",
  CALC_GC_PERCENT: "calcGcPercent",
  CALC_LENGTH: "calcLength",
  CALC_SCAFFOLD_L50: "calcScaffoldL50",
  CALC_SCAFFOLD_N50: "calcScaffoldN50",
  CALC_SEQUENCES: "calcSequences",
  CALC_TOP10_FRAC: "calcTop10Frac",
  CHROMOSOMES: "chromosomes",
  COVERAGE: "coverage",
  GC_PERCENT: "gcPercent",
  IS_REF: "isRef",
  LENGTH: "length",
  LEVEL: "level",
  MEASURED_LEVEL: "measuredLevel",
  ORGANISM_AVATAR: "organismAvatar",
  RELEASE_DATE: "releaseDate",
  REPORTED_VS_CALCULATED: "reportedVsCalculated",
  REPORTED_VS_CALCULATED_DETAIL: "reportedVsCalculatedDetail",
  SCAFFOLD_COUNT: "scaffoldCount",
  SCAFFOLD_L50: "scaffoldL50",
  SCAFFOLD_N50: "scaffoldN50",
  SOURCE: "source",
  STRAIN_NAME: "strainName",
  TAXONOMIC_GROUP: "taxonomicGroup",
  TAXONOMIC_LEVEL_CLASS: "taxonomicLevelClass",
  TAXONOMIC_LEVEL_DOMAIN: "taxonomicLevelDomain",
  TAXONOMIC_LEVEL_FAMILY: "taxonomicLevelFamily",
  TAXONOMIC_LEVEL_GENUS: "taxonomicLevelGenus",
  TAXONOMIC_LEVEL_KINGDOM: "taxonomicLevelKingdom",
  TAXONOMIC_LEVEL_ORDER: "taxonomicLevelOrder",
  TAXONOMIC_LEVEL_PHYLUM: "taxonomicLevelPhylum",
  TAXONOMIC_LEVEL_SPECIES: "taxonomicLevelSpecies",
  TAXONOMIC_LEVEL_STRAIN: "taxonomicLevelStrain",
  TAXONOMY_ID: "ncbiTaxonomyId",
};

export const HG_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ANALYZE_GENOME: "Action",
  ANNOTATION_STATUS: "Annotation Status",
  ASSEMBLY_COUNT: "Assemblies",
  ASSEMBLY_TAXONOMY_IDS: "Taxonomy ID",
  CALC_CONTIG_N50: "Calculated Contig N50",
  CALC_GC_PERCENT: "Calculated GC%",
  CALC_LENGTH: "Calculated Length",
  CALC_SCAFFOLD_L50: "Calculated L50",
  CALC_SCAFFOLD_N50: "Calculated N50",
  CALC_SEQUENCES: "Calculated Sequences",
  CALC_TOP10_FRAC: "Top-10 Share",
  CHROMOSOMES: "Chromosomes",
  COVERAGE: "Coverage",
  GC_PERCENT: "Reported GC%",
  IS_REF: "Is Ref",
  LENGTH: "Reported Length",
  LEVEL: "Declared Level",
  MEASURED_LEVEL: "Measured Level",
  ORGANISM_AVATAR: "",
  RELEASE_DATE: "Release Date",
  REPORTED_VS_CALCULATED: "Reported vs Calculated",
  REPORTED_VS_CALCULATED_DETAIL: "Differences",
  SCAFFOLD_COUNT: "Reported Scaffolds",
  SCAFFOLD_L50: "Reported L50",
  SCAFFOLD_N50: "Reported N50",
  SOURCE: "Source",
  STRAIN_NAME: "Strain Name",
  TAXONOMIC_GROUP: "Taxonomic Group",
  TAXONOMIC_LEVEL_CLASS: "Class",
  TAXONOMIC_LEVEL_DOMAIN: "Domain",
  TAXONOMIC_LEVEL_FAMILY: "Family",
  TAXONOMIC_LEVEL_GENUS: "Genus",
  TAXONOMIC_LEVEL_KINGDOM: "Kingdom",
  TAXONOMIC_LEVEL_ORDER: "Order",
  TAXONOMIC_LEVEL_PHYLUM: "Phylum",
  TAXONOMIC_LEVEL_SPECIES: "Species",
  TAXONOMIC_LEVEL_STRAIN: "Strain",
  TAXONOMY_ID: "Taxonomy ID",
};
