import { type CategoryConfig } from "@databiosphere/findable-ui/lib/common/categories/config/types";
import * as CATEGORY_CONFIG from "./categoryConfig";

export const CATEGORY_REGISTRY: Record<string, CategoryConfig> = {
  ACCESSION: CATEGORY_CONFIG.ACCESSION,
  ANNOTATION_STATUS: CATEGORY_CONFIG.ANNOTATION_STATUS,
  ASSEMBLY_TAXONOMY_IDS: CATEGORY_CONFIG.ASSEMBLY_TAXONOMY_IDS,
  COVERAGE: CATEGORY_CONFIG.COVERAGE,
  IS_REF: CATEGORY_CONFIG.IS_REF,
  LEVEL: CATEGORY_CONFIG.LEVEL,
  TAXONOMIC_GROUP: CATEGORY_CONFIG.TAXONOMIC_GROUP,
  TAXONOMIC_LEVEL_CLASS: CATEGORY_CONFIG.TAXONOMIC_LEVEL_CLASS,
  TAXONOMIC_LEVEL_DOMAIN: CATEGORY_CONFIG.TAXONOMIC_LEVEL_DOMAIN,
  TAXONOMIC_LEVEL_FAMILY: CATEGORY_CONFIG.TAXONOMIC_LEVEL_FAMILY,
  TAXONOMIC_LEVEL_GENUS: CATEGORY_CONFIG.TAXONOMIC_LEVEL_GENUS,
  TAXONOMIC_LEVEL_KINGDOM: CATEGORY_CONFIG.TAXONOMIC_LEVEL_KINGDOM,
  TAXONOMIC_LEVEL_ORDER: CATEGORY_CONFIG.TAXONOMIC_LEVEL_ORDER,
  TAXONOMIC_LEVEL_PHYLUM: CATEGORY_CONFIG.TAXONOMIC_LEVEL_PHYLUM,
  TAXONOMIC_LEVEL_SPECIES: CATEGORY_CONFIG.TAXONOMIC_LEVEL_SPECIES,
  TAXONOMIC_LEVEL_STRAIN: CATEGORY_CONFIG.TAXONOMIC_LEVEL_STRAIN,
  TAXONOMY_ID: CATEGORY_CONFIG.TAXONOMY_ID,
} as const;
