import { type ColumnConfig } from "@databiosphere/findable-ui/lib/config/entities";
import { type HGOrganismEntity } from "@highgen/apis/organism";
import {
  ASSEMBLY_COUNT,
  ASSEMBLY_TAXONOMY_IDS,
  ORGANISM_IMAGE,
  TAXONOMIC_GROUP,
  TAXONOMIC_LEVEL_CLASS,
  TAXONOMIC_LEVEL_DOMAIN,
  TAXONOMIC_LEVEL_FAMILY,
  TAXONOMIC_LEVEL_GENUS,
  TAXONOMIC_LEVEL_KINGDOM,
  TAXONOMIC_LEVEL_ORDER,
  TAXONOMIC_LEVEL_PHYLUM,
  TAXONOMIC_LEVEL_SPECIES,
} from "./columnDefs";

export const COLUMNS: ColumnConfig<HGOrganismEntity>[] = [
  ORGANISM_IMAGE,
  TAXONOMIC_LEVEL_SPECIES,
  ASSEMBLY_TAXONOMY_IDS,
  TAXONOMIC_GROUP,
  ASSEMBLY_COUNT,
  TAXONOMIC_LEVEL_DOMAIN,
  TAXONOMIC_LEVEL_KINGDOM,
  TAXONOMIC_LEVEL_PHYLUM,
  TAXONOMIC_LEVEL_CLASS,
  TAXONOMIC_LEVEL_ORDER,
  TAXONOMIC_LEVEL_FAMILY,
  TAXONOMIC_LEVEL_GENUS,
];
